# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotfiles < Formula
  desc "Declarative dotfiles manager and AI tmux workspace orchestrator"
  homepage "https://github.com/entelecheia/dotfiles-v2"
  version "2.67.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/entelecheia/dotfiles-v2/releases/download/v2.67.0/dot_2.67.0_darwin_amd64.tar.gz"
      sha256 "2d277d02b29c8ab9005a64fb8b3b84b0ac0a7e5bbfd0a2e5d126498d06ed6705"

      define_method(:install) do
        bin.install "dot"
        bin.install_symlink "dot" => "dotfiles"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/entelecheia/dotfiles-v2/releases/download/v2.67.0/dot_2.67.0_darwin_arm64.tar.gz"
      sha256 "36898162891f37679816aaef7cc54d2185f11d82d338bb263f398c8c50259d75"

      define_method(:install) do
        bin.install "dot"
        bin.install_symlink "dot" => "dotfiles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/entelecheia/dotfiles-v2/releases/download/v2.67.0/dot_2.67.0_linux_amd64.tar.gz"
      sha256 "68797e6cef3c38a3cd3f6e394e432ed6a9efd3ade57f5de1feb8eff8b107b3cc"
      define_method(:install) do
        bin.install "dot"
        bin.install_symlink "dot" => "dotfiles"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/entelecheia/dotfiles-v2/releases/download/v2.67.0/dot_2.67.0_linux_arm64.tar.gz"
      sha256 "5c443320d2262fb15c285d593ff4e0692a9b2ec4a3a928badb4066a702860341"
      define_method(:install) do
        bin.install "dot"
        bin.install_symlink "dot" => "dotfiles"
      end
    end
  end

  test do
    system "#{bin}/dot", "version"
  end
end
