# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotfiles < Formula
  desc "Declarative dotfiles manager and AI tmux workspace orchestrator"
  homepage "https://github.com/entelecheia/dotfiles-v2"
  version "2.70.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/entelecheia/dotfiles-v2/releases/download/v2.70.10/dot_2.70.10_darwin_amd64.tar.gz"
      sha256 "114aec2ddb5d4e3b381789000af01d9cfede2afd54f0ac9d957eace109daca68"

      define_method(:install) do
        bin.install "dot"
        bin.install_symlink "dot" => "dotfiles"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/entelecheia/dotfiles-v2/releases/download/v2.70.10/dot_2.70.10_darwin_arm64.tar.gz"
      sha256 "eaa5d97d32ec6b76a0302a0eb0898cda046eefe5024ad38024eb6f00fce9ebf6"

      define_method(:install) do
        bin.install "dot"
        bin.install_symlink "dot" => "dotfiles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/entelecheia/dotfiles-v2/releases/download/v2.70.10/dot_2.70.10_linux_amd64.tar.gz"
      sha256 "429b90062a4872810fbb916b42e95bf9ef07ab40aefbfa6238cdf0b730404c92"
      define_method(:install) do
        bin.install "dot"
        bin.install_symlink "dot" => "dotfiles"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/entelecheia/dotfiles-v2/releases/download/v2.70.10/dot_2.70.10_linux_arm64.tar.gz"
      sha256 "3b78a67c80e6cb64afb354b57f472c042b4df84fde0aea1807468d4c0711c776"
      define_method(:install) do
        bin.install "dot"
        bin.install_symlink "dot" => "dotfiles"
      end
    end
  end

  test do
    system "#{bin}/dot", "version"
  end
end
